# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-22.04

    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy PDF
        run: cp -r ./spielereader.pdf ./docs/

      - name: Deploy
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: docs/
          remote_path: /var/www/vhosts/901154.jweiland-hosting.de/httpdocs/spielereader.org
          remote_host: 18.198.166.35
          remote_user: u901154
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}
