# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-24.04

    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Copy PDF
        run: cp -r ./spielereader.pdf ./docs/

      - name: Deploy
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: docs/
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}
